version: "3.9"
services:
  postgres_db:
    image: postgres:11
    restart: always
    command: -p 5435
    env_file:
      - .env
    expose:
      - 5435
    ports:
      - "5435:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: